var music = ["../src/sound/Akiba.mp3",
    "../src/sound/Chaos_Nya.mp3",
    "../src/sound/Scared_Play_Secret_Place.mp3",
    "../src/sound/SnowDream.mp3",
    "../src/sound/Usagi_Flap.mp3",
    "../src/sound/人类祈祷记录.mp3",
    "../src/sound/柔和之光.mp3"],
    posts = ["../src/img/Akiba.jpg",
    "../src/img/ChaosNya.jpg",
    "../src/img/ScaredPlaySecretPlace.jpg",
    "../src/img/SnowDream.jpg",
    "../src/img/UsahiFlap.jpg",
    "../src/img/人类祈祷记录.jpg",
    "../src/img/柔和之光.jpg"],
    playIcon = '../src/img/doing.png',
    stopIcon = '../src/img/stop.png';